services:
  minio:
    image: minio/minio:latest
    container_name: typecord-minio
    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: typecord
      MINIO_ROOT_PASSWORD: troque-essa-senha

    volumes:
      - typecord_minio:/data

    command: server /data --console-address ":9001"

volumes:
  typecord_minio: