export type GatewayEvent =
  | "READY"
  | "MESSAGE_CREATE"
  | "MESSAGE_UPDATE"
  | "MESSAGE_DELETE"
  | "MESSAGE_REACTION_ADD"
  | "MESSAGE_REACTION_REMOVE"
  | "GUILD_CREATE"
  | "GUILD_UPDATE"
  | "GUILD_DELETE"
  | "GUILD_ROLE_CREATE"
  | "GUILD_ROLE_UPDATE"
  | "GUILD_ROLE_DELETE"
  | "GUILD_BAN_ADD"
  | "GUILD_BAN_REMOVE"
  | "INVITE_CREATE"
  | "INVITE_DELETE"
  | "CHANNEL_CREATE"
  | "CHANNEL_UPDATE"
  | "CHANNEL_DELETE"
  | "GUILD_MEMBER_ADD"
  | "GUILD_MEMBER_UPDATE"
  | "GUILD_MEMBER_REMOVE"
  | "USER_UPDATE"
  | "PRESENCE_UPDATE"
  | "TYPING_START"
  | "NOTIFICATION_CREATE"
  | "VOICE_STATE_UPDATE"
  | "SOUNDBOARD_PLAY";

export interface GatewayPayload<T = unknown> {
  op: number;
  t: GatewayEvent;
  s: number;
  d: T;
}
